### ISSUE TITLE
ImportError: cannot import name 'set_seed'

### ISSUE THREAD

**Issue by PINTO0309** [yas-sim/openvino-ep-enabled-onnxruntime#1]
### Environment
- Ubuntu 18.04 x86_64
- onnxruntime 1.3.0
- OpenVINO 2020.2
- Python 3.6
- cmake 3.17.3

### Problem that arose
Use a pre-built .whl installer or a self-built and generated .whl installer Then, the following error message is displayed and onnxruntime cannot be imported It was not. This may be an issue that is directly unrelated to the purpose of this repository, which is to enable OpenVINO EP, but if you can give me some information, I would appreciate it.
```console
$ python3 onnxruntime-test.py
Traceback (most recent call last):
  File "onnxruntime-test.py", line 5, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode, OrtDevice, SessionIOBinding
ImportError: cannot import name 'set_seed'
```

**Comment by yas-sim** [comment]
Thanks for reporting. I'll look into this.

**Comment by yas-sim** [comment]
I could replicate the issue on my new Ubuntu 18.04 machine.
It seems you'll got this error if you have installed `onnxruntime` beforehand.
My machine had following 3 onnx related packages after I installed the prebuilt onnxruntime-openvino package (and the error happened).
```
 onnx  1.6.0
 onnxruntime  1.2.0
 onnxruntime-openvino 1.3.0
```
The program worked after I uninstall both `onnxruntime` and `onnxruntime-openvino` once, and then re-installed the `onnxruntime-openvino`.

BTW, I found that the `ResNet50` models does't work on Ubuntu+Python configuration. The `Resnet50` model could run on Win+CPP, Win+Python, Ubuntu+CPP but Ubuntu+Python.
Please try with the other models such as `Resnet18`, `squeezenet` or `googlenet`.

Thanks,

**Comment by PINTO0309** [comment]
Thank you! I'll investigate later when I have time.

**Comment by PINTO0309** [comment]
I tried the advice you gave me and was able to get it to work properly.
